name: selfspy
description: Modern activity monitoring in Dart - elegant syntax with excellent performance
version: 1.0.0
homepage: https://github.com/selfspy/selfspy3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.8.3
  sqlite3: ^2.1.0
  yaml: ^3.1.2
  crypto: ^3.0.3
  intl: ^0.19.0
  logging: ^1.2.0
  async: ^2.11.0
  collection: ^1.17.2
  meta: ^1.9.1
  ffi: ^2.1.0

dev_dependencies:
  test: ^1.24.6
  dart_code_metrics: ^5.7.6
  very_good_analysis: ^5.1.0

executables:
  selfspy: selfspy
  selfstats: selfstats  
  selfviz: selfviz

platforms:
  linux:
  macos:
  windows: